### ISSUE TITLE
Tutorial error

### ISSUE THREAD

**Issue by atul7cloudyuga** [theupdateframework/tuf#898] opened 2019-08-14 12:27 UTC
**Description of issue or feature request**:
Unable to follow steps in tutorial. Not sure why this error is coming. Can someone help

**Current behavior**:
Getting an error in importing private_root_key

>>> private_root_key = import_rsa_privatekey_from_file("keystore/root_key")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_tool.py", line 3185, in import_rsa_privatekey_from_file
    return repo_lib.import_rsa_privatekey_from_file(filepath, password)
  File "/usr/local/lib/python2.7/dist-packages/tuf/repository_lib.py", line 819, in import_rsa_privatekey_from_file
    filepath, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/interface.py", line 350, in import_rsa_privatekey_from_file
    scheme, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/keys.py", line 974, in import_rsakey_from_private_pem
    pem, password)
  File "/usr/local/lib/python2.7/dist-packages/securesystemslib/pyca_crypto_keys.py", line 625, in create_rsa_public_and_private_from_pem
    ' cannot be generated from the encrypted PEM string: ' + str(e))
securesystemslib.exceptions.CryptoError: RSA (public, private) tuple cannot be generated from the encrypted PEM string: Password was not given but private key is encrypted

I am getting this error with cli tutorials too which i assume are same kind error as i was getting in python based advance tutorial

$ repo.py --sign tufkeystore/mykey --role myrole
Enter a password for the encrypted key ('tufkeystore/mykey'):
Error: 'tufkeystore/mykey' cannot be imported, possibly because an invalid key file is given or the decryption password is incorrect.

$ repo.py --sign tufkeystore/root_key --role root
Enter a password for the encrypted key ('tufkeystore/root_key'):
Error: 'tufkeystore/root_key' cannot be imported, possibly because an invalid key file is given or the decryption password is incorrect.

**Comment by atul7cloudyuga** [comment] 2019-08-14 13:26
I am getting this error with cli tutorials too which i assume are same kind error as i was getting in python based advance tutorial

$ repo.py --sign tufkeystore/mykey --role myrole
Enter a password for the encrypted key ('tufkeystore/mykey'): 
Error: 'tufkeystore/mykey' cannot be imported, possibly because an invalid key file is given or the decryption password is incorrect.

$ repo.py --sign tufkeystore/root_key --role root
Enter a password for the encrypted key ('tufkeystore/root_key'): 
Error: 'tufkeystore/root_key' cannot be imported, possibly because an invalid key file is given or the decryption password is incorrect.

**Comment by lukpueh** [comment] 2019-08-14 14:11
Thanks for filing an issue, @atul7cloudyuga. Unfortunately I cannot reproduce your problem with the information you provided. Can you tell me which version of TUF you have installed, and how you installed it?

Also, your traceback seems truncated, were you not asked to enter a password when calling `import_rsa_privatekey_from_file`?

**Comment by atul7cloudyuga** [comment] 2019-08-16 05:37
> Thanks for filing an issue, @atul7cloudyuga. Unfortunately I cannot reproduce your problem with the information you provided. Can you tell me which version of TUF you have installed, and how you installed it?
> 

I am on Ubuntu 18.04 . I installed tuf by "pip install securesystemslib[crypto,pynacl] tuf". I got following message after installation
"Successfully installed asn1crypto-0.24.0 cffi-1.12.3 colorama-0.4.1 cryptography-2.7 enum34-1.1.6 ipaddress-1.0.22 iso8601-0.1.12 pycparser-2.19 pynacl-1.3.0 securesystemslib-0.11.3 six-1.12.0 tuf-0.11.1"


> Also, your traceback seems truncated, were you not asked to enter a password when calling `import_rsa_privatekey_from_file`?

No i was not prompted for password.  Instead of being prompted for password, i got the following error messages as mentioned in logs above.

Also i mentioned error from CLI examples too. There also i am getting almost same error.

**Comment by adityasaky** [comment] 2019-08-19 05:14
@lukpueh I'm actually able to reproduce this on my Mac. I've narrowed it down to how I install `tuf` in the workspace. If I run `pip install tuf` and run the tutorial in the python console, I face the same issue and I'm not prompted for a password.

The last release of `tuf` on PyPI is from June 18th, 2018 (https://pypi.org/project/tuf/0.12.dev2/#description). This commit https://github.com/theupdateframework/tuf/commit/4ee3537d6da574b03707d818de0aaa5b98ee8228#diff-9f585d5478a17bd9e0f6cd5f7484ab60 was made on June 21st, 2018 and is actually catching `CryptoError`. I'm guessing you're unable to reproduce it because you tried it with `tuf` that's aligned with `tuf/develop`?

**Comment by lukpueh** [comment] 2019-09-03 12:43
Thanks for troubleshooting, @adityasaky! This issue has been fixed in https://github.com/theupdateframework/tuf/pull/755. 

@atul7cloudyuga, please use the latests pre-release from PyPI, i.e.:
```
pip install tuf==0.11.2.dev3
```

or consider a [development installation](
https://github.com/theupdateframework/tuf/blob/develop/docs/CONTRIBUTORS.rst#development-installation).

**Closed as completed by lukpueh** 2019-09-03 12:43 UTC
