### ISSUE TITLE
`Repository.writeall()` does not "write all" and may leave repo in inconsistent state 

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#958] opened 2019-11-13 15:48 UTC
**Description of issue or feature request**:

The [name and docstring](https://github.com/theupdateframework/tuf/blob/42c8d116d9f842a8eb111a8d7289ebf785fd9b88/tuf/repository_tool.py#L220-L226) of `Repository.writeall()`-classmethod and its [commented use in the tuf tutorial](https://github.com/theupdateframework/tuf/blame/42c8d116d9f842a8eb111a8d7289ebf785fd9b88/docs/TUTORIAL.md#L440-L444), suggest that it writes all the metadata that needs to be written upon a metadata change, when in practice it only writes metadata that is marked as dirty.

This may leave the repository metadata in an inconsistent state, as is the case in above linked tutorial part.

**Current behavior**:

`writeall` only writes metadata that is marked as dirty, ignoring metadata interdependencies, i.e. timestamp needs to be re-written if snapshot changes,  snapshot needs to be rewritten if targets or delegated targets changes, which may leave a repository in an inconsistent state.

**Expected behavior**:
Two options are conceivable:

- Update documentation but above all the tutorial to clarify that `writeall` might require a prior call to `mark_dirty` (I will add a quick fix in #775)

- Update `writeall` to indeed write all the metadata that is required to be written upon any metadata change (preferred solution).

**Comment by JustinCappos** [comment] 2019-11-13 17:14
I agree with the second option.  Let's make writeall actually write all!

**Comment by lukpueh** [comment] 2019-11-14 10:42
Thanks for you comment, @JustinCappos! Can we briefly together look at the metadata inter-dependencies to make sure that `writeall` will indeed write all?

As far as I can see the following inter-dependencies exist:
- a change of keys in a **delegating role**, i.e. root or any delegating targets role, requires to bump the version and renew the signature of the **delegated role**, whose key was changed:
  - (change root keys in **root** --> bump version and re-sign **root**)
  - change timestamp key in **root** --> bump version and re-sign **timestamp**
  - change snapshot key in **root** --> bump version and re-sign **snapshot**
  - change targets key in **root** --> bump version and re-sign **targets**
  - change delegated targets key in **delegating targets** --> bump version and re-sign **delegated targets**
- any change in **targets or delegated targets** (including above) requires to update the relevant targets version number (and optionally its length and hashes) in **snapshot**, bump snapshot's own version number, and renew snapshot's signature
- any change in **snapshot** (including above) requires to update snapshot's version number in **timestamp**, bump timestamp's own version number, and renew timestamp's signature

Note how above rules may create longer update chains, e.g. changing targets keys in **root**, must re-write **targets**, which in turn must re-write **snapshot**, which in turn must re-write **timestamp**. 

Can someone double-check if this list is correct and comprehensive? cc @mnm678, @SantiagoTorres, @trishankatdatadog.

**Comment by trishankatdatadog** [comment] 2019-11-14 18:40
@lukpueh Sounds about right to me. Way back then, we used to write _everything_ to disk regardless of whether a role metadata file was "dirty" or not. @SantiagoTorres and I noticed this in our PyPI experiments, and we asked to write only dirty files going forward. I'm guessing there are bugs in that implementation logic.

**Comment by woodruffw** [comment] 2020-03-05 21:24
Submitting my support for this as the PEP 458 implementor -- having to manually mark things as dirty makes it easy to make small mistakes.

**Comment by jku** [comment] 2022-02-16 12:02
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

Note that we don't currently provide repository tools that would handle a "write all" case: the improved Metadata API does make it a lot easier to manage this, see examples/repo_example/ and https://github.com/vmware-labs/repository-editor-for-tuf for examples.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 12:02 UTC
