### ISSUE TITLE
Targets.delegate() creates different objects for the same role

### ISSUE THREAD

**Issue by sechkova** [theupdateframework/tuf#1061] opened 2020-06-29 12:19 UTC
**Description of issue or feature request**:
Each time `Targets.delegate()` is called, a new `Repository.Targets` object is created.

If `delegate()` is called twice to create two delegations to the same role, this will result in two `Targets` objects with the same `Targets._rolename` and only one `roledb` record. 

Likewise, only one of the two delegated `Targets` objects will be referenced by the top-level `Targets` object.

For example in case of the following delegation graph:
```
targets -> unclaimed-1 -> role1
targets -> unclaimed-2 -> role1
```

The result is two different `Targets` objects for 'role1' :
```
In [7]: repository.targets._delegated_roles                                                                                                                                                                        
Out[7]: 
{'unclaimed-1': <tuf.repository_tool.Targets at 0x7f936e3094d0>,
 'unclaimed-2': <tuf.repository_tool.Targets at 0x7f93678ff9d0>,
 'role1': <tuf.repository_tool.Targets at 0x7f936789da10>}

In [8]: repository.targets('unclaimed-2')._delegated_roles                                                                                                                                                         
Out[8]: {'role1': <tuf.repository_tool.Targets at 0x7f93678d2e50>}

In [9]: repository.targets('unclaimed-1')._delegated_roles                                                                                                                                                         
Out[9]: {'role1': <tuf.repository_tool.Targets at 0x7f936789da10>}
```

**Current behavior**:
In case of a delegation, it is unclear if the `Targets` class represents a single role or a delegation since a separate object is created for each delegation but mapped to the same role (rolename).

Only one of the created objects can be referenced by the top-level targets object.

**Expected behavior**:
Clarify the `Repository.Targets` class :
- do not create more than one object for the same delegated role
or
- revise the class to more appropriately represent a delegation

Related issue: #820

**Comment by jku** [comment] 2022-02-16 09:37
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 09:37 UTC
