### ISSUE TITLE
Revise intended and actual behavior of  Repository's `status()` method

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/tuf#955] opened 2019-11-12 10:25 UTC
**Description of issue or feature request**:

The [`status()`](https://github.com/theupdateframework/tuf/blob/9b93c0bcccffef25b7603318297b2504ede3fd33/tuf/repository_tool.py#L379-L421)-method on the `repository_tool.Repository`-class, wraps [`repository_lib._log_status_of_top_level_roles`](https://github.com/theupdateframework/tuf/blob/9b93c0bcccffef25b7603318297b2504ede3fd33/tuf/repository_lib.py#L1776-L1919), and logs status information about the repository.

**Current behavior:**

This is a non-comprehensive list of concerns identified in these functions:

* `status` is a non-intuitive name for a function that changes and then logs the changed status. E.g. when calling `status` on unsigned metadata, `status` signs the metadata and informs you about the existence of those signatures.

* The control flow is unclear, e.g. `_log_status_of_top_level_roles` may log the following information for any top level role:

  (1) `"ROLENAME role contains K / N public keys"`
  (2) `"ROLENAME role contains K / N signing keys"`
  (3) `"ROLENAME role contains K / N signatures"`

  However the information is shown:
  (1) for roles that have `K < N` public keys,
  (2) for roles that have `K >= N` public keys, and no signatures, and `K < N` signing keys,
  (3) for roles that are processed before `_generate_and_write_metadata` and `_log_status` fails for a role, including the role that failed. The order of processed roles is: root, targets, snapshot, timestamp.

* There is unnecessarily complicated and repetitive code, e.g.:
  ```python
  # This construct is repeated for every role
  root_is_dirty = None
  if 'root' in dirty_rolenames:
    root_is_dirty = True

  else:
    root_is_dirty = False
  ```
  ...should be ...
  ```python
  root_is_dirty = False
  if 'root' in dirty_rolenames:
    root_is_dirty = True
  ```
  ... or just ...
  ```python
  root_is_dirty = 'root' in dirty_rolenames
  ```

  And since this construct is repeated for every top-level role, the best way would be a helper function. 

  ```python
   is_role_dirty(rolename)
  ```

* The separation of `status` and `_log_status_of_top_level_roles` function is not obvious. 
  `status` creates a temporary directory and passes it to `_log_status_of_top_level_roles` so that  metadata created in `_log_status_of_top_level_roles` is written to the temporary directory. After logging the status, the temporary directory is removed. `status` is the only function that calls `_log_status_of_top_level_roles`.

* The code documentation does not suffice to understand if the implementation matches the intended behavior.

**Expected behavior**:
- Identify intended behavior
- Update code documentation to clearly convey intended behavior
- Update implementation to match code documentation (if necessary)
- Simplify code (strive for readability!!)

**Comment by jku** [comment] 2022-02-16 12:04
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 12:04 UTC
