### ISSUE TITLE
Improve exception hierarchy

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/tuf#967] opened 2019-12-16 16:35 UTC
**Description of issue or feature request**:

Improve the exception hierarchy in TUF.

**Current behavior**:

Right now, every exception in TUF is a `NoWorkingMirrorError()`, which makes for very misleading error messages, to say the least, especially for front-end users.

**Expected behavior**:

Every exception should say exactly what the real error was.

**Comment by lukpueh** [comment] 2020-04-15 08:56
Slightly related bad error message: https://github.com/lukpueh/tuf/commit/e3e39cfa6a3d83fc6798c85015eac0110ec56367

**Comment by jku** [comment] 2022-02-16 11:58
I think we are far better about it now:
* there are fewer errors: only ones that we handle or that we actually expect clients (or future repository tools) to handle
* there is a hierarchy:
  * The different RepositoryErrors are useful but for a client they all mean "something is wrong on the repository side metadata and the issue is something we can't fix: A refresh later may help"
  * There are multiple DownloadErrors which for a client are all the same: "something goes wrong during download. trying again later might work"
  
  Closing, please open a new one if there are still issues

**Closed as completed by jku** 2022-02-16 11:58 UTC
Labels: enhancement
