### ISSUE TITLE
Passing HTTP header to client.updater

### ISSUE THREAD

**Issue by thangld322** [theupdateframework/tuf#1011] opened 2020-04-02 14:52 UTC
**Description of issue or feature request**:
I'm using client.updater to update file from tuf_server like this:
```python
            repository_mirrors = {'mirror1': {'url_prefix': tuf_server,
                                              'metadata_path': metadata_path,
                                              'targets_path': targets_path,
                                              'confined_target_dirs': ['']}}

            updater = tuf.client.updater.Updater('tufrepo', repository_mirrors)
```
The problem is tuf_server uses API Key for authentication. My question is how can I pass API Key to client.updater so it can access tuf_server.

**Current behavior**:

401 Unauthorized

**Expected behavior**:

200 Success

**Comment by SantiagoTorres** [comment] 2020-04-02 16:06
Hi @thangld322 ! While I think your issue is important to fix on our side (i.e., to provide a mechanism for for authenticating with the repository's transport) I also wanted to suggest that you take a look at `requests`'s support for `.netrc` fiiles for authentication. This way you can make things work while we discuss and prepare a solution on our end :)

**Comment by jku** [comment] 2022-02-16 09:54
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

Specifically on HTTP headers: current client (tuf.ngclient) is configurable in that you can provide a Fetcher implementation of your own: making a copy of the default RequestsFetcher (or even deriving from it) in your app makes this possible.


### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 09:54 UTC
Labels: enhancement
