### ISSUE TITLE
Rewrite _generate_and_write_metadata function and the way it's called

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/tuf#1070] opened 2020-07-06 12:11 UTC
**Description of issue or feature request**:
The `_generate_and_write_metadata` function in the `tuf/repository_lib.py` file,  even if private contains too many arguments.
In one of the pr discussions https://github.com/theupdateframework/tuf/pull/1031#discussion_r448785300, where we are adding 4 additional arguments @jku count them to be 15!!

Additionally, we should rewrite  the way we call `_generate_and_write_metadata` because repository_tool's `writeall` function already performs the whole role case handling that's also done in this function, and so does `repository_lib._log_status_of_top_level_roles`, which is a whole different story (see #955).

**Current behavior**:
We do most of the whole role case handling in the `writeall` function from  the`tuf.repository_tool.py` file and still pass a lot of context from it to the `_generate_and_write_metadata` and thus we have a function with 15 arguments!

**Expected behavior**:
Use only `writeall` or `_generate_and_write_metadata` function to do the role case handling and call the relevant `generate_X_metadata` function where X is the role.

**Comment by joshuagl** [comment] 2020-07-06 14:13
It does take too many arguments. I believe that this is, at least in part, an artefact of how OO usage was minimised in the codebase.
`repository_lib` provides library functions for interacting with and creating a repository, but explicitly doesn't use any classes. Therefore all required state must be passed in to each method.

The tuf maintainers are discussing a refactoring effort for tuf where I expect we will take care of issues like this.
My expectation is that we'll build on the OO "low-level" APIs currently WIP in #1060, building higher-level APIs for repository management and clients, with some shared utility code between the two. I'd also like us to follow the example of other TUF implementations (such as Notary and Tough) and have a CLI tool which can be used to create and manage repositories.

**Comment by jku** [comment] 2022-02-16 09:36
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 09:36 UTC
