### ISSUE TITLE
Unexpected warning when calling `Repository.status()`

### ISSUE THREAD

**Issue by joshuagl** [theupdateframework/tuf#1199] opened 2020-11-05 11:01 UTC
**Description of issue or feature request**:

Since e0086d6 repository_lib warns when metadata is written without signatures.
The Repository class in repository_tool has a `status()` method which generates the metadata for a repository in order to report various information about the repository metadata, i.e.

'targets' role contains 0 / 1 public keys.
'snapshot' role contains 0 / 1 public keys.
'timestamp' role contains 0 / 1 public keys.
'root' role contains 2 / 2 signatures.
'targets' role contains 0 / 1 signatures.

Since the change to repository_lib above, the output of status() now warns about "Unsigned metadata objects", for example:

'targets' role contains 0 / 1 public keys.
'snapshot' role contains 0 / 1 public keys.
'timestamp' role contains 0 / 1 public keys.
'root' role contains 2 / 2 signatures.
Unsigned metadata object: {'signed': {'version': 1, 'expires': '2021-02-02T17:55:23Z', 'targets': {}, 'delegations': {'keys': {}, 'roles': []}, '_type': 'targets', 'spec_version': '1.0.0'}, 'signatures': []}
'targets' role contains 0 / 1 signatures.

**Current behavior**:

`Repository.status()` prints a warning

**Expected behavior**:

`Repository.status()` does not print a warning

**Comment by joshuagl** [comment] 2020-11-05 11:02
See related issue on more generally changing the behaviour of `Repository.status()` https://github.com/theupdateframework/tuf/issues/955

**Comment by joshuagl** [comment] 2020-11-05 11:04
@sechkova [suggested](https://github.com/theupdateframework/tuf/pull/1197#issuecomment-722297776) in the abandoned #1197 that we might just filter the logs to remove that warning as part of the `Repository.status()` operations

```
def _log_status_of_top_level_roles(targets_directory, metadata_directory,
    repository_name, storage_backend):
  ...

  filter = type('', (logging.Filter,), {'filter': staticmethod(lambda r: not r.msg.startswith('Unsigned metadata object'))})
  logger.addFilter(filter)
  ...
  // do whatever the function does
  ...
  logger.removeFilter(filter)
```

**Comment by sechkova** [comment] 2020-11-05 14:34
@joshuagl already mentioned my short term fix proposal for this concrete issue.

On the long term I want to mention the two broader issues leading to this one here:
1)  Behaviour of Repository.status() as mentioned [above](https://github.com/theupdateframework/tuf/issues/1199#issuecomment-722306065)
2) General behaviour of the framework towards unsigned metadata

What I mean by 2 is:
Partially signed and/or unsigned metadata is allowed in some cases some of which to my knowledge are:
- creating metadata on one host and signing it on another
- taking shortcuts in tests
- the `status` example here

I can't say I have an exhaustive list of all use cases and I haven't found it described anywhere which brings headaches to a developer who has to make a related decision 🙄 

So my point is: can a disclaimer/docstring/?? be added to the implementation saying when partially/fully unsigned metadata is allowed and is not compromising security?

**Comment by jku** [comment] 2021-11-30 08:35
client label seemed like a mistake, removing

**Comment by jku** [comment] 2022-02-16 08:33
Closing this issue as it was filed against (what is now known as) the legacy codebase: issue seems to not be relevant anymore. Please re-open or file a new issue if you feel that the issue is revelant to current python-tuf.

### More details

Current source code (and upcoming 1.0 release) only contains the modern components
 * a low-level Metadata API (`tuf.api`) and 
 * `tuf.ngclient` that implements the client workflow, 

Legacy components (e.g. tuf.client, tuf.repository_tool, tuf.repository_lib as well as the repo and client scripts) are no longer included. See [announcement](https://github.com/theupdateframework/python-tuf/blob/develop/docs/1.0.0-ANNOUNCEMENT.md) and [API reference](https://theupdateframework.readthedocs.io/en/latest/api/api-reference.html) for more details.

**Closed as completed by jku** 2022-02-16 08:33 UTC
